### PR TITLE
Laravel 11.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 11.x.

**Before merging**, you need to:

- Checkout the `l11-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: The latest version of Laravel has a dependency for `phpunit/phpunit` of `^10.5`. If you would like to also upgrade your tests, you may run the [PHPUnit 10 Shift](https://laravelshift.com/upgrade-phpunit-10) for free.

**Comment by laravel-shift** [comment]
:warning: Shift detected GitHub Actions which run jobs using a version `matrix`. Shift attempted to [update your configuration](https://github.com/torchlight-api/torchlight-laravel/pull/54/commits/42f4238e1d37fd1fccfc9f8a87035189580ddca0?w=1) for Laravel 11. However, you should review these changes to ensure the desired combination of versions are built for your package.

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/torchlight-laravel.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "torchlight/torchlight-laravel": "dev-l11-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by PH7-Jack** [comment]
Are there any updates here?

**Comment by valpuia604** [comment]
Please merge this..

**Comment by naykel76** [comment]
What is the situation here? will this be merged?

I have been unsucessfull in using this fork

**Comment by miomech** [comment]
@aarondfrancis I'm certain you're very busy but it would be awesome if we could get this PR merged in. 
Don't intend to sound rude in the slightest but this package seems like it's been left to the wayside. 

If you need an extra hand I'd be more than happy to help out with at least reviewing PR's. This is an awesome package and it would suck for it to be abandoned. Thanks!

**Comment by dasundev** [comment]
@aarondfrancis We're waiting for this PR merge.

**Comment by xuchunyang** [comment]
I tried the pull request locally and found that it works fine for me; I can see the highlights. This is my first time using Torchlight and I only tried `x-torchlight-code` blade compoent.

**Comment by robdekort** [comment]
Hello there. Plus one for this please. I just moved a customer over to the paid version of Torchlight. However development seems a bit stale unfortunately. We would love to update our project to Laravel 11 soon. Would appreciate an update. Thanks! 🙏

**Comment by aarondfrancis** [comment]
Thanks for your patience!

**Comment by robdekort** [comment]
Amazing, thank you.

**Comment by miomech** [comment]
Thank You!

**Pull request merged**
